EPMLABSBRN-254 fix for commit-msg hook

diff --git a/.githooks/commit-msg b/.githooks/commit-msg
--- a/.githooks/commit-msg
+++ b/.githooks/commit-msg
@@ -1,12 +1,11 @@
-#!/usr/bin/env bash
-
-current_branch="$(git rev-parse --abbrev-ref HEAD)"
+#!/bin/bash
 
 # regex to validate in commit msg
-commit_regex='(EPMLABSBRN)(-\d+)'
+commit_regex='EPMLABSBRN-[0-9]{1,3} .*$'
+
 error_msg="Aborting commit. Your commit message is missing a JIRA issue name, see example: 'EPMLABSBRN-111'"
 
-if ! grep -iqE "$commit_regex" "$1"; then
-    echo "$error_msg" >&2
+if ! grep -P "$commit_regex" "$1"; then
+    echo -e "$error_msg" >&2
     exit 1
 fi
